# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  run:
    cmds:
      - ng serve --configuration=production
    silent: true
  rund:
    cmds:
      - ng serve --disable-host-check --configuration=production
    silent: true

  build:
    cmds:
      - ng build --configuration=production
    silent: true
