# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - ng serve --disable-host-check
    silent: true
  run:
    cmds:
      - node server.js
    silent: true
  runp:
    cmds:
      - ng serve --disable-host-check --configuration=production
    silent: true

  build:
    cmds:
      - git pull
      - npm install
      - ng build --configuration=production
    silent: true
