# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - npx ng serve --configuration=development
    silent: true

  dev:
    desc: Serve with development environment (environment.dev.ts)
    cmds:
      - npx ng serve --configuration=development
    silent: true

  prod:
    desc: Serve with production environment (environment.prod.ts)
    cmds:
      - npx ng serve --disable-host-check --configuration=production
    silent: true
  run:
    cmds:
      - node server.js
    silent: true

  build:
    cmds:
      - git pull
      - npm install
      - ng build --configuration=production
    silent: true
